#!/usr/bin/env bash
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd)"
TARGET="${SCRIPT_DIR}/../docs/dependency-graph.md"

contents="$(pnpm depcruise src --include-only ^src --config --output-type mermaid)"
echo "" > "${TARGET}"
echo "\`\`\`mermaid" >> "${TARGET}"
echo "${contents}" >> "${TARGET}"
echo "\`\`\`" >> "${TARGET}"
